-- Migration 0001: Users, Projects, ActionItems.
-- Data model is docs/Command_Center_Architecture.md section E.
-- Users and Projects are included only because ActionItems references them.
-- The remaining tables (Clients, Contacts, Meetings, SOPs, BillingPeriods,
-- TimeEntries, Invoices, Templates, Reports, TimeSavedLog, SlipsCaught) arrive
-- in later migrations as their modules get built.
--
-- Ids are TEXT UUIDs generated by the API with crypto.randomUUID().
-- Timestamps are ISO 8601 UTC strings. Dates are YYYY-MM-DD.

PRAGMA foreign_keys = ON;

-- Users: id, email, display_name, role, created_at
CREATE TABLE users (
  id           TEXT PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  role         TEXT NOT NULL DEFAULT 'owner',
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Projects: id, client_id, name, phase, status, owner_id, start_date,
--           target_close, next_milestone, description, created_at, updated_at
--
-- client_id is carried now but left unconstrained: the Clients table does not
-- exist yet and SQLite cannot add a foreign key to an existing table. The
-- migration that creates Clients rebuilds this table with the constraint.
CREATE TABLE projects (
  id             TEXT PRIMARY KEY,
  client_id      TEXT,
  name           TEXT NOT NULL,
  phase          TEXT NOT NULL DEFAULT 'initiating'
                 CHECK (phase IN ('initiating','planning','executing','monitoring','closing')),
  status         TEXT NOT NULL DEFAULT 'on_track'
                 CHECK (status IN ('on_track','at_risk','blocked','done')),
  owner_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  start_date     TEXT,
  target_close   TEXT,
  next_milestone TEXT,
  description    TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_phase ON projects (phase);
CREATE INDEX idx_projects_client ON projects (client_id);

-- ActionItems: id, title, context, owner, deadline, status, source,
--              meeting_id, project_id, asana_task_gid, created_at, completed_at
--
-- owner is free text so items can name a teammate who has no Users row.
-- owner_id is the optional link to a Users row when there is one.
-- meeting_id is carried now but unconstrained: Meetings arrives with the
-- Meetings module and that migration rebuilds this table with the constraint.
CREATE TABLE action_items (
  id             TEXT PRIMARY KEY,
  title          TEXT NOT NULL,
  context        TEXT,
  owner          TEXT,
  owner_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  deadline       TEXT,
  status         TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open','waiting','blocked','done','ambiguous')),
  source         TEXT NOT NULL DEFAULT 'manual'
                 CHECK (source IN ('meeting','email','manual')),
  meeting_id     TEXT,
  project_id     TEXT REFERENCES projects(id) ON DELETE SET NULL,
  asana_task_gid TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  completed_at   TEXT
);

-- The Today cockpit and the overdue and due-today views all filter on
-- status plus deadline, so index that pair.
CREATE INDEX idx_action_items_status_deadline ON action_items (status, deadline);
CREATE INDEX idx_action_items_project ON action_items (project_id);
CREATE INDEX idx_action_items_meeting ON action_items (meeting_id);
CREATE INDEX idx_action_items_deadline ON action_items (deadline);
