<script lang="ts">
	import ReportBody from '$lib/components/ReportBody.svelte';
	import { formatDay } from '$lib/format';
	import { reportMeta } from '$lib/types';
	import type { PageData } from './$types';

	/**
	 * The printable report.
	 *
	 * PDF export is the browser's own print-to-PDF over clean printable HTML,
	 * which is what architecture section D asks for and what keeps this off
	 * Cloudflare's paid Browser Rendering product. See D53.
	 *
	 * The report itself is ReportBody, the same component the screen route uses.
	 * Only the page around it changes. That is deliberate: a print stylesheet can
	 * drift from the screen it was written for, but a shared component cannot
	 * show two different numbers.
	 *
	 * Nothing auto-prints. A page that opens a print dialog by itself takes the
	 * decision away from the reader, and this URL is also just a clean read-only
	 * view worth having on its own.
	 */

	let { data }: { data: PageData } = $props();

	const meta = $derived(reportMeta(data.type));

	const generated = $derived(
		new Intl.DateTimeFormat('en-US', {
			timeZone: 'America/Denver',
			dateStyle: 'medium',
			timeStyle: 'short'
		}).format(new Date(data.generated_at))
	);

	const backHref = $derived(
		meta.windowed
			? `/reports/${data.type}?from=${data.from}&to=${data.to}`
			: `/reports/${data.type}`
	);
</script>

<svelte:head>
	<title>{meta.title}</title>
	<meta name="robots" content="noindex" />
</svelte:head>

<nav class="bar">
	<a href={backHref}>Back to the report</a>
	<button type="button" onclick={() => window.print()}>Print or save as PDF</button>
</nav>

<article class="sheet">
	<header>
		<p class="brand">Command Center</p>
		<h1>{meta.title}</h1>
		<p class="summary">{meta.summary}</p>
		<dl class="stamp">
			{#if meta.windowed}
				<div><dt>Covering</dt><dd>{formatDay(data.from)} to {formatDay(data.to)}</dd></div>
			{/if}
			<div><dt>As of</dt><dd>{formatDay(data.today)}</dd></div>
			<div><dt>Generated</dt><dd>{generated} Mountain Time</dd></div>
		</dl>
	</header>

	<ReportBody type={data.type} data={data.data} today={data.today} />

	<footer>
		<p>
			Generated by Command Center on {generated} Mountain Time.
			{#if meta.windowed}
				Figures cover {formatDay(data.from)} to {formatDay(data.to)}.
			{/if}
			Aging and overdue counts are as of {formatDay(data.today)} and will move with the date.
		</p>
	</footer>
</article>

<style>
	.bar {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-3);
		align-items: center;
		padding: var(--space-3) var(--space-4);
		border-bottom: 1px solid var(--border-thin);
		background: var(--surface-card);
	}

	.bar a,
	.bar button {
		display: inline-flex;
		align-items: center;
		/* 44px tap-target floor, D22. */
		min-height: 44px;
		padding: 0 var(--space-4);
		border: 1px solid var(--border-control);
		border-radius: var(--radius-sm);
		background: var(--surface-card);
		color: var(--text-body);
		font-family: var(--font-sans);
		font-size: var(--text-sm);
		text-decoration: none;
		cursor: pointer;
	}

	.bar button {
		background: var(--navy);
		border-color: var(--navy);
		color: var(--text-inverse);
	}

	.bar a:hover {
		background: var(--surface-hover);
	}

	.bar button:hover {
		background: var(--navy-700);
	}

	.bar a:focus-visible,
	.bar button:focus-visible {
		outline: 2px solid var(--navy);
		outline-offset: 2px;
	}

	.sheet {
		max-width: 60rem;
		margin: 0 auto;
		padding: var(--space-6) var(--space-4);
		display: flex;
		flex-direction: column;
		gap: var(--space-5);
	}

	header {
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
		padding-bottom: var(--space-4);
		border-bottom: 2px solid var(--navy);
	}

	.brand {
		margin: 0;
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		letter-spacing: var(--tracking-label);
		text-transform: uppercase;
		color: var(--text-secondary);
	}

	h1 {
		margin: 0;
		font-size: var(--text-xl);
		font-weight: var(--weight-medium);
	}

	.summary {
		margin: 0;
		font-size: var(--text-sm);
		color: var(--text-secondary);
	}

	.stamp {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-4);
		margin: var(--space-2) 0 0;
	}

	.stamp div {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.stamp dt {
		font-size: var(--text-xs);
		text-transform: uppercase;
		letter-spacing: var(--tracking-label);
		color: var(--text-secondary);
	}

	.stamp dd {
		margin: 0;
		font-family: var(--font-mono);
		font-size: var(--text-sm);
	}

	footer {
		padding-top: var(--space-4);
		border-top: 1px solid var(--border-thin);
	}

	footer p {
		margin: 0;
		font-size: var(--text-xs);
		color: var(--text-secondary);
	}

	@media print {
		/* The controls are for the screen. They are not part of the document. */
		.bar {
			display: none;
		}

		.sheet {
			max-width: none;
			margin: 0;
			padding: 0;
			gap: 14pt;
		}

		header {
			border-bottom: 1.5pt solid #000;
			padding-bottom: 8pt;
			gap: 3pt;
		}

		h1 {
			font-size: 16pt;
		}

		.brand,
		.summary {
			font-size: 8pt;
		}

		.stamp {
			gap: 16pt;
			margin-top: 4pt;
		}

		.stamp dt {
			font-size: 7pt;
		}

		.stamp dd {
			font-size: 9pt;
		}

		/* The stamp repeats on nothing, so the footer carries the provenance on
		   the last page. Keep it off a page of its own. */
		footer {
			break-before: avoid;
			padding-top: 8pt;
			border-top: 0.5pt solid #999;
		}

		footer p {
			font-size: 7.5pt;
		}
	}
</style>
