/**
 * Adds a `scheduled` export to the built Worker.
 *
 * @sveltejs/adapter-cloudflare emits a worker whose default export has only
 * `fetch`. Cloudflare Cron Triggers invoke `scheduled`, so a trigger against
 * that worker fails. This script runs after `vite build` and stitches the two
 * together:
 *
 *   1. the adapter's output is moved aside to _app-worker.js
 *   2. the cron handler is bundled to _scheduled.js
 *   3. a new _worker.js re-exports the app's fetch and adds scheduled
 *   4. both new files are added to .assetsignore so neither is ever served
 *
 * It is deliberately loud. If the adapter's output shape changes, this fails the
 * build rather than silently shipping a worker with no cron handler.
 */
import { existsSync, readFileSync, renameSync, writeFileSync, appendFileSync } from 'node:fs';
import { build } from 'esbuild';

const DIR = '.svelte-kit/cloudflare';
const WORKER = `${DIR}/_worker.js`;
const APP = `${DIR}/_app-worker.js`;
const SCHEDULED = `${DIR}/_scheduled.js`;

function fail(message) {
	console.error(`\n[wrap-worker] ${message}\n`);
	process.exit(1);
}

if (!existsSync(WORKER)) {
	fail(`${WORKER} not found. Did vite build run, and is wrangler.toml still targeting Workers?`);
}

const original = readFileSync(WORKER, 'utf8');

if (original.includes('__COMMAND_CENTER_WRAPPED__')) {
	fail('the worker is already wrapped. Run a clean build.');
}

if (!/export\s*\{[^}]*as default\s*\}|export default/.test(original)) {
	fail('could not find a default export in the adapter output. The adapter shape has changed.');
}

renameSync(WORKER, APP);

// The cron handler and everything it imports, bundled for the workerd runtime.
await build({
	entryPoints: ['src/lib/server/scheduled.ts'],
	bundle: true,
	format: 'esm',
	platform: 'neutral',
	target: 'es2022',
	conditions: ['workerd', 'worker', 'browser'],
	outfile: SCHEDULED,
	logLevel: 'warning'
});

writeFileSync(
	WORKER,
	`// __COMMAND_CENTER_WRAPPED__
// Generated by scripts/wrap-worker.js. Do not edit.
// The app worker below is the unmodified adapter-cloudflare output.
import app from './_app-worker.js';
import { handleScheduled } from './_scheduled.js';

export default {
	fetch: app.fetch,
	scheduled: handleScheduled
};
`
);

// Neither generated file may be served as a public asset.
appendFileSync(`${DIR}/.assetsignore`, '\n_app-worker.js\n_scheduled.js\n');

console.log('[wrap-worker] added a scheduled export to _worker.js');
